### ISSUE TITLE
install-conky-lua-archers-v1.sh will not work

### ISSUE THREAD

**Issue by stepborc** [ArchMergeLinux/amd-xfce#1]
I'd try to install XFCE on ArchMergD. When running script 300-software-AUR-repo-v1.sh I get a lot of errors. When disabling the line 'sh AUR/install-conky-lua-archers-v*.sh' the installation runs without any problems. I didn't understand where the problem is.

I'll install it on VirtualBox.

**Comment by archmerge** [comment]
The solution is here : 
Do in your folder of amd-xfce
`git pull`
Script **AUR/install-conky-lua-archers-v*.sh** was not executable

[Forum](https://archmergefor
um.com/viewtopic.php?f=35&t=321&p=1213&hilit=conky+lua+archers#p1213)
